### ISSUE TITLE
Docker Issue: Windows

### ISSUE THREAD

**Issue by dkaiser42** [paser-group/continuous-secsoft#1]
I don't have required prerequisites to run the Docker Desktop on my laptop. The prerequisite I'm missing is the right version of Windows, those being Windows 10 Pro/Enterprise (15063+) or Windows 10 Home (19018+). What would suggest I do?

**Comment by akondrahman** [comment]
In that case you will be using your laptop. Install tools in your own machine instead of using the Docker image.

**Comment by akondrahman** [comment]
@dkaiser42 : what is your windows configuration?
