### ISSUE TITLE
Gitlab is broken?

### ISSUE THREAD

**Issue by bnorthern42** [paser-group/continuous-secsoft#7]
![image](https://user-images.githubusercontent.com/54911506/131080131-5a2069e0-b554-4d9a-b5aa-948edab9c05b.png)
Keep getting error when trying to push to my repo in gitlab: 

"remote: Your subscription has been downgraded. You didn't renew your subscription so it was downgraded to the GitLab Core Plan."

Is remote pushing not supported, and if not, how does one add files? I can not seem to drag & drop files like github allows, also there is no way of creating a branch from the web GUI. 

(never used gitlab, been on github for years)

**Comment by akondrahman** [comment]
Please contact Jared Jennings.

**Comment by akondrahman** [comment]
This is fixed now.

**Comment by bnorthern42** [comment]
If people are still having trouble, (tested with IntelliJ, but I'm sure it's the same for pyCharm from Jetbrains) The git plugin allows you to push/pull to SSH url for your gitlab. Especially works well as Github allows you to 'drag & drop' directories at a time while gitlab does not for the Web gui.
